// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-FWSKs-mbGQJ1nKb-ztmj6p9TZRHnT94',
    appId: '1:772702267067:web:9c2ead5d27573a053fab9e',
    messagingSenderId: '772702267067',
    projectId: 'know-your-expense',
    authDomain: 'know-your-expense.firebaseapp.com',
    storageBucket: 'know-your-expense.appspot.com',
    measurementId: 'G-C35HLMMMNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyKm5KArhYnhacbBTBPR0xdQoKY0kbQBk',
    appId: '1:772702267067:android:cdb4cb2062d770cc3fab9e',
    messagingSenderId: '772702267067',
    projectId: 'know-your-expense',
    storageBucket: 'know-your-expense.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvLQNHNlcE0WlnEaMXCHAOpfsmTUGv-Sc',
    appId: '1:772702267067:ios:64e2274957dcb77e3fab9e',
    messagingSenderId: '772702267067',
    projectId: 'know-your-expense',
    storageBucket: 'know-your-expense.appspot.com',
    iosClientId: '772702267067-0r0jq9hpi4vq6g3mrm2n4uk7ifcelj4r.apps.googleusercontent.com',
    iosBundleId: 'com.knowinforms.kye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvLQNHNlcE0WlnEaMXCHAOpfsmTUGv-Sc',
    appId: '1:772702267067:ios:64e2274957dcb77e3fab9e',
    messagingSenderId: '772702267067',
    projectId: 'know-your-expense',
    storageBucket: 'know-your-expense.appspot.com',
    iosClientId: '772702267067-0r0jq9hpi4vq6g3mrm2n4uk7ifcelj4r.apps.googleusercontent.com',
    iosBundleId: 'com.knowinforms.kye',
  );
}
